DROP TABLE IF EXISTS players;

CREATE TABLE players (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  faceit_id VARCHAR(40) NOT NULL UNIQUE,
  nickname VARCHAR(20) NOT NULL,
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  deaths INT UNSIGNED NOT NULL DEFAULT 0,
  wins INT UNSIGNED NOT NULL DEFAULT 0,
  matches INT UNSIGNED NOT NULL DEFAULT 0
);

